/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.formdev.flatlaf.FlatDarkLaf;
import dao.UsuarioDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static javax.security.auth.callback.ConfirmationCallback.INFORMATION;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import utilerias.Sesion;
import utilerias.Encriptador; // Importación de la utilería de encriptación

/**
 *
 * @author Gilberto
 */
public class LoginView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    private int intentos = 0;
    private boolean passwordVisible = false;

    public LoginView() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/icons/coding.png")).getImage());
        this.setTitle("KING HOTEL");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jUsernameLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        jIniciarBtn = new javax.swing.JButton();
        jCancelarBtn = new javax.swing.JButton();
        jInicioLabel2 = new javax.swing.JLabel();
        jViewPasswordBtn = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jregistrar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setForeground(new java.awt.Color(255, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        jUsernameLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jUsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        jUsernameLabel.setText("USUARIO:");
        jPanel1.add(jUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, 20));

        jPasswordLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        jPasswordLabel.setText("CONTRASEÑA:");
        jPanel1.add(jPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 140, 20));

        jUsernameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 280, 50));

        jIniciarBtn.setBackground(new java.awt.Color(0, 51, 102));
        jIniciarBtn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jIniciarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jIniciarBtn.setText("Iniciar sesión");
        jIniciarBtn.addActionListener(this::jIniciarBtnActionPerformed);
        jPanel1.add(jIniciarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 280, 40));

        jCancelarBtn.setBackground(new java.awt.Color(153, 153, 153));
        jCancelarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jCancelarBtn.setText("Cancelar");
        jCancelarBtn.addActionListener(this::jCancelarBtnActionPerformed);
        jPanel1.add(jCancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 280, 30));

        jInicioLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jInicioLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jInicioLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicioLabel2.setText("INICIO DE SESIÓN");
        jPanel1.add(jInicioLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 500, 30));

        jViewPasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        jViewPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar.png"))); // NOI18N
        jViewPasswordBtn.setBorder(null);
        jViewPasswordBtn.setBorderPainted(false);
        jViewPasswordBtn.addActionListener(this::jViewPasswordBtnActionPerformed);
        jPanel1.add(jViewPasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 40, 30));

        jPasswordField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPasswordField.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPasswordField.setSelectionColor(new java.awt.Color(255, 255, 204));
        jPasswordField.addActionListener(this::jPasswordFieldActionPerformed);
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 280, 50));

        jregistrar1.setBackground(new java.awt.Color(0, 51, 102));
        jregistrar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jregistrar1.setForeground(new java.awt.Color(255, 255, 255));
        jregistrar1.setText("Registrarte");
        jregistrar1.addActionListener(this::jregistrar1ActionPerformed);
        jPanel1.add(jregistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/King Hotel (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, 70));

        jProgressBar.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jIniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciarBtnActionPerformed
        String user = jUsernameField.getText().trim();
        String pass = new String(jPasswordField.getPassword());

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa usuario y contraseña!");
            return;
        }
        
        // 🔥 CORRECCIÓN: Encriptamos la contraseña plana a SHA-256 usando la utilería
        String passEncriptada = Encriptador.encriptarSHA256(pass);
        
        UsuarioDAO dao = new UsuarioDAO();
        // Le pasamos la contraseña encriptada (64 caracteres) para que coincida con la BD corregida
        String rol = dao.validarLogin(user, passEncriptada); 
        
        if (rol != null) {
            Sesion.usuarioActivo = user;
            Sesion.rolActivo = rol;
            intentos = 0;

            JOptionPane.showMessageDialog(this, 
                    "Bienvenido " + user + " (" + rol + ")");

            iniciarProgressBar(); 
            
        } else {
            intentos++;
            JOptionPane.showMessageDialog(this, 
                    "Credenciales incorrectas. Intento " + intentos + "/3");
            
            jUsernameField.setText("");
            jPasswordField.setText("");
            
            if (intentos >= 3) {
                bloquearBoton();
            }
        }
    }//GEN-LAST:event_jIniciarBtnActionPerformed

    private void jCancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarBtnActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que quieres salir?",
            "Salir",
            JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jCancelarBtnActionPerformed

    private void jregistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregistrar1ActionPerformed
        FrmRegistro registro = new FrmRegistro();
        registro.setVisible(true);
        this.dispose(); // cierra login mientras se registra
    }//GEN-LAST:event_jregistrar1ActionPerformed

    private void jViewPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewPasswordBtnActionPerformed
        if (passwordVisible) {
            // ocultar contraseña
            jPasswordField.setEchoChar('•');
            jViewPasswordBtn.setIcon(
                    new ImageIcon(getClass().getResource("/icons/cerrar.png"))
            );
            passwordVisible = false;
        } else {
            // mostrar contraseña
            jPasswordField.setEchoChar((char) 0);
            jViewPasswordBtn.setIcon(
                    new ImageIcon(getClass().getResource("/icons/abrir.png"))
            );
            passwordVisible = true;
        }
    }//GEN-LAST:event_jViewPasswordBtnActionPerformed

    private void iniciarProgressBar() {
        jProgressBar.setValue(0);
        jProgressBar.setString("");
        jProgressBar.setStringPainted(true);

        Timer timer = new Timer(20, null);

        timer.addActionListener(new ActionListener() {
            private int value = 0;
            private final int total = 100;

            @Override
            public void actionPerformed(ActionEvent e) {
                value += 1;
                jProgressBar.setValue(value);

                if (value >= total) {
                    ((Timer) e.getSource()).stop();

                    SwingUtilities.invokeLater(() -> {
                        new MenuPrincipalForm(Sesion.rolActivo).setVisible(true);
                        dispose();
                    });
                }
            }
        });

        timer.start();
    }

    private void bloquearBoton() {
        jIniciarBtn.setEnabled(false);
        jUsernameField.setEnabled(false);
        jPasswordField.setEnabled(false);
        jViewPasswordBtn.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());  // Tema oscuro (recomendado)
            UIManager.put("Button.arc", 12);              // botones más redondeados
            UIManager.put("Component.arc", 10);           // componentes en general
            UIManager.put("TextComponent.arc", 10);       // campos de texto redondeados

            // Color de acento (azul brillante moderno)
            UIManager.put("Component.accentColor", new java.awt.Color(59, 130, 246)); // azul #3b82f6

        } catch (Exception ex) {
            System.err.println("Error al aplicar FlatLaf: " + ex.getMessage());
        }
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelarBtn;
    private javax.swing.JButton jIniciarBtn;
    private javax.swing.JLabel jInicioLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JButton jViewPasswordBtn;
    private javax.swing.JButton jregistrar1;
    // End of variables declaration//GEN-END:variables

    private Icon getIconUrl(String url, int w, int h) {
        return new ImageIcon(new ImageIcon(getClass().getResource(url))
                .getImage().getScaledInstance(w, h, 0));
    }
}
